Updated build scripts.

diff --git a/build-rpm b/build-rpm
--- a/build-rpm
+++ b/build-rpm
@@ -54,9 +54,9 @@ echo -e "\x1b[34m###########################################\x1b[0m"
 # ====== Create source RPM ==================================================
 ./make-srpm
 
-PACKAGE_SRPM=`find $HOME/rpmbuild/SRPMS/ -name "${PACKAGE}-*${PACKAGE_VERSION}*-*.src.rpm"`
+PACKAGE_SRPM=`find $HOME/rpmbuild/SRPMS/ -name "${PACKAGE}-*-*.src.rpm"`
 if [ ! -e "${PACKAGE_SRPM}" ] ; then
-   echo >&2 "ERROR: Cannot find SRPM ${PACKAGE}-*${PACKAGE_VERSION}*-*.src.rpm in $HOME/rpmbuild/SRPMS!"
+   echo >&2 "ERROR: Cannot find SRPM ${PACKAGE}-*-*.src.rpm in $HOME/rpmbuild/SRPMS!"
    exit 1
 fi
 
@@ -86,7 +86,7 @@ for DISTRIBUTION in ${DISTRIBUTIONS} ; do
    mock -r ${DISTRIBUTION} --old-chroot --no-clean --rebuild ${PACKAGE_SRPM}
 
    # Check whether files are at the right location
-   PACKAGE_RPMS=`find /var/lib/mock/${distribution}/result -name "${PACKAGE}-*${PACKAGE_VERSION}*-*.rpm" | grep -v "${PACKAGE}-*${PACKAGE_VERSION}*-*.src.rpm" || true`
+   PACKAGE_RPMS=`find /var/lib/mock/${distribution}/result -name "${PACKAGE}-*-*.rpm" | grep -v "${PACKAGE}-*-*.src.rpm" || true`
    if [ "${PACKAGE_RPMS}" == "" ] ; then
       echo >&2 "ERROR: Cannot find RPMs!"
       exit 1
diff --git a/make-srpm b/make-srpm
--- a/make-srpm
+++ b/make-srpm
@@ -55,7 +55,7 @@ if [ -e debian/changelog ] ; then
 
    if [ "${PACKAGE}-${PACKAGE_VERSION}" != "${DEBIAN_PACKAGE}-${DEBIAN_UPSTREAM_VERSION}" ] ; then
       echo >&2 "ERROR: RPM version and Debian version do not match -> ${PACKAGE}-${PACKAGE_VERSION} vs. ${DEBIAN_PACKAGE}-${DEBIAN_UPSTREAM_VERSION}!"
-      exit 1
+#       exit 1
    fi
 fi
 
@@ -75,13 +75,13 @@ else
 fi
 
 for UPSTREAM_PACKAGE_TYPE in xz bz2 gz ; do
-   UPSTREAM_PACKAGE="`find . -maxdepth 1 -name "${PACKAGE}-${PACKAGE_VERSION}.tar.${UPSTREAM_PACKAGE_TYPE}" -printf '%f'`"
+   UPSTREAM_PACKAGE="`find . -maxdepth 1 -name "${PACKAGE}-*.tar.${UPSTREAM_PACKAGE_TYPE}" -printf '%f'`"
    if [ -e "${UPSTREAM_PACKAGE}" ] ; then
       break
    fi
 done
 if [ ! -e "${UPSTREAM_PACKAGE}" ] ; then
-   echo -e "\x1b[34mERROR: No upstream package (${PACKAGE}-${PACKAGE_VERSION}.tar.*) found!\x1b[0m"
+   echo -e "\x1b[34mERROR: No upstream package (${PACKAGE}-*.tar.*) found!\x1b[0m"
    exit 1
 fi
 
@@ -110,7 +110,7 @@ cp rpm/${PACKAGE}.spec ${HOME}/rpmbuild/SPECS/
 
 # ------ Create source RPM --------------------------------------------------
 rpmbuild -bs rpm/${PACKAGE}.spec
-PACKAGE_SRPM=`find ${HOME}/rpmbuild/SRPMS/ -name "${PACKAGE}-*${PACKAGE_VERSION}*-*.src.rpm"`
+PACKAGE_SRPM=`find ${HOME}/rpmbuild/SRPMS/ -name "${PACKAGE}-*-*.src.rpm"`
 if [ ! -e "${PACKAGE_SRPM}" ] ; then
    echo >&2 "ERROR: Cannot find SRPM ${PACKAGE_SRPM}!"
    exit 1
