Build script updates.

diff --git a/build-deb b/build-deb
--- a/build-deb
+++ b/build-deb
@@ -51,11 +51,11 @@ echo -e "\x1b[34mUPSTREAM_VERSION:     ${UPSTREAM_VERSION}\x1b[0m"
 echo -e "\x1b[34mPLAIN_VERSION:        ${PLAIN_VERSION}\x1b[0m"
 echo -e "\x1b[34m######################################################################\x1b[0m"
 
-if [ ! -e ./debian.conf ] ; then
-   echo >&2 "ERROR: debian.conf does not exist -> no configuration for the new package!"
+if [ ! -e ./packaging.conf ] ; then
+   echo >&2 "ERROR: packaging.conf does not exist -> no configuration for the new package!"
    exit 1
 fi
-. ./debian.conf
+. ./packaging.conf
 
 if [ "${OVERRIDE_PACKAGE_DISTRIBUTION}" != "" ] ; then
    PACKAGE_DISTRIBUTION="${OVERRIDE_PACKAGE_DISTRIBUTION}"
diff --git a/make-deb b/make-deb
--- a/make-deb
+++ b/make-deb
@@ -71,11 +71,11 @@ echo -e "\x1b[34mUPSTREAM_VERSION:     ${UPSTREAM_VERSION}\x1b[0m"
 echo -e "\x1b[34mPLAIN_VERSION:        ${PLAIN_VERSION}\x1b[0m"
 echo -e "\x1b[34m######################################################################\x1b[0m"
 
-if [ ! -e ./debian.conf ] ; then
-   echo >&2 "ERROR: debian.conf does not exist -> no configuration for the new package!"
+if [ ! -e ./packaging.conf ] ; then
+   echo >&2 "ERROR: packaging.conf does not exist -> no configuration for the new package!"
    exit 1
 fi
-. ./debian.conf
+. ./packaging.conf
 
 
 # ====== Run warp-and-sort tool =============================================
@@ -91,33 +91,22 @@ fi
 echo -e ""
 echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Creating upstream package ======================================\x1b[0m"
 echo -e ""
+if [ "${SKIP_PACKAGE_SIGNING}" != "" -a ${SKIP_PACKAGE_SIGNING} -eq 1 ] ; then
+   ./make-upstream-package ${PACKAGE} ${UPSTREAM_VERSION} "${MAKE_DIST}" -skip-signing
+else
+   ./make-upstream-package ${PACKAGE} ${UPSTREAM_VERSION} "${MAKE_DIST}"
+fi
+
 for UPSTREAM_PACKAGE_TYPE in xz bz2 gz ; do
-   UPSTREAM_PACKAGE="`find . -maxdepth 1 -name "${PACKAGE}-*.${UPSTREAM_PACKAGE_TYPE}" -printf '%f'`"
+   UPSTREAM_PACKAGE="`find . -maxdepth 1 -name "${PACKAGE}-${UPSTREAM_VERSION}.tar.${UPSTREAM_PACKAGE_TYPE}" -printf '%f'`"
    if [ -e "${UPSTREAM_PACKAGE}" ] ; then
       break
    fi
 done
-if [ ! -e "${UPSTREAM_PACKAGE}" ]; then
-   rm -f ${PACKAGE}-*.gz ${PACKAGE}"_"*.gz ${PACKAGE}-*.bz2 ${PACKAGE}"_"*.bz2 ${PACKAGE}-*.xz ${PACKAGE}"_"*.xz
-   echo -e "\x1b[34m------ Running MAKE_DIST ... ------\x1b[0m"
-   echo "\$ $MAKE_DIST"
-   eval "$MAKE_DIST"
-
-   echo -e "\x1b[34m------ Looking for upstream package ... ------\x1b[0m"
-   for UPSTREAM_PACKAGE_TYPE in xz bz2 gz ; do
-      UPSTREAM_PACKAGE="`find . -maxdepth 1 -name "${PACKAGE}-*.${UPSTREAM_PACKAGE_TYPE}" -printf '%f'`"
-      if [ -e "${UPSTREAM_PACKAGE}" ] ; then
-         break
-      fi
-   done
-   if [ ! -e "${UPSTREAM_PACKAGE}" ] ; then
-      echo -e "\x1b[34mERROR: No upstream package (${PACKAGE}-*, type ${UPSTREAM_PACKAGE_TYPE}) found!\x1b[0m"
-      exit 1
-   fi
+if [ ! -e "${UPSTREAM_PACKAGE}" ] ; then
+   echo -e "\x1b[34mERROR: No upstream package (${PACKAGE}-${UPSTREAM_VERSION}.tar.*) found!\x1b[0m"
+   exit 1
 fi
-echo -e ""
-echo -e "\x1b[34m==> Upstream package is ${UPSTREAM_PACKAGE} (type is ${UPSTREAM_PACKAGE_TYPE})\x1b[0m"
-echo -e ""
 
 
 # ====== Sign upstream source package =======================================
diff --git a/make-ppa b/make-ppa
--- a/make-ppa
+++ b/make-ppa
@@ -25,9 +25,12 @@ DPUT=0
 DPUT_DISTRIBUTIONS="precise trusty xenial bionic cosmic disco   unstable"
 
 while [ $# -gt 0 ] ; do
-   if [ "$1" == "dput" -o "$1" == "all" ] ; then
+   if [ "$1" == "dput" ] ; then
       DPUT=1
-   elif [ "$1" == "copr" -o "$1" == "all" ] ; then
+   elif [ "$1" == "copr" ] ; then
+      COPR=1
+   elif [ "$1" == "all" ] ; then
+      DPUT=1
       COPR=1
    else
       echo >&2 "Usage: $0 [dput] [copr] [all]"
@@ -36,13 +39,18 @@ while [ $# -gt 0 ] ; do
    shift
 done
 
+if [ ${DPUT} -eq 0 -a ${COPR} -eq 0 ] ; then
+   COPR=1
+   DPUT=1
+fi
+
 
 # ====== Build source packages ==============================================
 ./clean-deb
 if [ ${DPUT} -ne 0 ] ; then
-   . ./debian.conf
+   . ./packaging.conf
    if [ "${NOT_TARGET_DISTRIBUTIONS}" == "" ] ; then
-      echo >&2 "ERROR: Define NOT_TARGET_DISTRIBUTIONS in debian.conf!"
+      echo >&2 "ERROR: Define NOT_TARGET_DISTRIBUTIONS in packaging.conf!"
       exit 1
    fi
    buildForDistribution=""
@@ -66,6 +74,9 @@ fi
 if [ ${COPR} -ne 0 ] ; then
    if [ -e rpm -o -e ./make-srpm ] ; then
       ./make-srpm || exit 1
+   else
+      echo >&2 "ERROR: RPM files not found!"
+      exit 1
    fi
 fi
 
