Updated build scripts.

diff --git a/ci/build b/ci/build
--- a/ci/build
+++ b/ci/build
@@ -21,44 +21,111 @@
 
 # ###### Linux ##############################################################
 if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
-   if [ "${TOOL}" == "compile" ] ; then
-      echo "###### Compiling ... ##################################################"
 
+   # ====== Docker ==========================================================
+   if [ "${DOCKER}" != "" ] ; then
+
+      if [ "${TOOL}" == "compile" ] ; then
+         echo "###### Compiling ... ##################################################"
+
+         if [ -e CMakeLists.txt ] ; then
+            sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake . $@
+         elif [ -e configure.ac -o -e configure.in ] ; then
+            if [ -e bootstrap ] ; then
+               sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./bootstrap
+               sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
+            elif [ -e autogen.sh ] ; then
+               sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./autogen.sh
+            else
+               sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
+            fi
+         else
+            echo >&2 "WARNING: No build system detected. Trying to just call \"make\" ..."
+         fi
+
+         cores=`sudo docker exec ubuntu-test env LANG=C.UTF-8 getconf _NPROCESSORS_ONLN 2>/dev/null || true`
+         if [ $cores -gt 1 ] ; then
+            MAKEFLAGS="-j${cores}"
+         fi
+         sudo docker exec ubuntu-test env LANG=C.UTF-8 MAKEFLAGS=${MAKEFLAGS} make   # VERBOSE=1
+
+      elif [ "${TOOL}" == "pbuilder" ] ; then
+         echo "###### Running pbuilder ... ###########################################"
+         sudo docker exec ubuntu-test env LANG=C.UTF-8 sed -e 's/SKIP_PACKAGE_SIGNING=0/SKIP_PACKAGE_SIGNING=1/g' -i debian.conf
+         sudo docker exec ubuntu-test env LANG=C.UTF-8 eatmydata ./build-deb
+
+      elif [ "${TOOL}" == "mock" ] ; then
+         echo "###### Running mock ... ###############################################"
+         release=`sudo docker exec -t ubuntu-test bash -c "LANG=C.UTF-8 ; cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\"" | sed -e "s/[^0-9]//g"`
+         arch=`sudo docker exec -t ubuntu-test env LANG=C.UTF-8 uname -m | sed -e "s/[^0-9a-zA-Z_-+]//g"`
+         sudo docker exec ubuntu-test env LANG=C.UTF-8  ./build-rpm fedora-${release}-${arch}
+
+      else
+         echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
+         exit 1
+      fi
+
+
+   # ====== Travis CI standard Ubuntu Linux machine =========================
+   # That is: not using Docker
+   else
+      # ====== Configure ====================================================
       if [ -e CMakeLists.txt ] ; then
-         sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake . $@
+         env CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake . $@
       elif [ -e configure.ac -o -e configure.in ] ; then
          if [ -e bootstrap ] ; then
-            sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./bootstrap
-            sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
+            env CC=${COMPILER_C} CXX=${COMPILER_CXX} ./bootstrap
+            env CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
          elif [ -e autogen.sh ] ; then
-            sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./autogen.sh
+            env CC=${COMPILER_C} CXX=${COMPILER_CXX} ./autogen.sh
          else
-            sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
+            env CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
          fi
       else
          echo >&2 "WARNING: No build system detected. Trying to just call \"make\" ..."
       fi
-
-      cores=`sudo docker exec ubuntu-test env LANG=C.UTF-8 getconf _NPROCESSORS_ONLN 2>/dev/null || true`
+      cores=`getconf _NPROCESSORS_ONLN 2>/dev/null || true`
       if [ $cores -gt 1 ] ; then
          MAKEFLAGS="-j${cores}"
       fi
-      sudo docker exec ubuntu-test env LANG=C.UTF-8 MAKEFLAGS=${MAKEFLAGS} make   # VERBOSE=1
 
-   elif [ "${TOOL}" == "pbuilder" ] ; then
-      echo "###### Running pbuilder ... ###########################################"
-      sudo docker exec ubuntu-test env LANG=C.UTF-8 sed -e 's/SKIP_PACKAGE_SIGNING=0/SKIP_PACKAGE_SIGNING=1/g' -i debian.conf
-      sudo docker exec ubuntu-test env LANG=C.UTF-8 eatmydata ./build-deb
+      # ====== Compile ======================================================
+      if [ "${TOOL}" == "compile" ] ; then
+         env MAKEFLAGS=${MAKEFLAGS} make   # VERBOSE=1
 
-   elif [ "${TOOL}" == "mock" ] ; then
-      echo "###### Running mock ... ###############################################"
-      release=`sudo docker exec -t ubuntu-test bash -c "LANG=C.UTF-8 ; cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\"" | sed -e "s/[^0-9]//g"`
-      arch=`sudo docker exec -t ubuntu-test env LANG=C.UTF-8 uname -m | sed -e "s/[^0-9a-zA-Z_-+]//g"`
-      sudo docker exec ubuntu-test env LANG=C.UTF-8  ./build-rpm fedora-${release}-${arch}
+      # ====== Coverity Scan ================================================
+      elif [ "${TOOL}" == "coverity" ] ; then
+         # ------ Build -----------------------------------------------------
+         cd coverity
+         export PATH="coverity/$(ls -d cov*)/bin:$PATH"
+         cd ..
 
-   else
-      echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
-      exit 1
+         env MAKEFLAGS=${MAKEFLAGS} cov-build --dir cov-int make
+         tar czf coverity-results.tar.gz cov-int
+         ls -l coverity-results.tar.gz
+
+         # ------ Upload results --------------------------------------------
+         if [ "${TRAVIS_BRANCH}" == "${COVERITY_SCAN_BRANCH}" ] ; then
+            curl --form token=${COVERITY_SCAN_TOKEN} \
+              --form email=${COVERITY_SCAN_NOTIFICATION_EMAIL} \
+              --form file=@coverity-results.tar.gz \
+              --form version="master branch head" \
+              --form description="$(git log -1|head -1)" \
+              https://scan.coverity.com/builds?project=${COVERITY_PROJECT}
+            CURL_RESULT=$?
+            echo "curl returned ${CURL_RESULT}"
+            if [ $CURL_RESULT -ne 0 ]; then
+               echo >&2 "ERROR: Upload to Coverity Scan failed; curl returned ${CURL_RESULT}!"
+               exit 1
+            fi
+         else
+            echo >&2 "###### NOTE: This branch \"${TRAVIS_BRANCH}\" is not the scan branch \"${COVERITY_SCAN_BRANCH}\"! Skipping upload! ######"
+         fi
+
+      else
+         echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
+         exit 1
+      fi
    fi
 
 
diff --git a/ci/install b/ci/install
--- a/ci/install
+++ b/ci/install
@@ -25,82 +25,86 @@ UBUNTU_MIRROR="archive.ubuntu.com"
 
 # ###### Linux ##############################################################
 if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
-   # ====== Ubuntu Linux ====================================================
-   if [ "${VARIANT}" == "ubuntu" -o "${VARIANT}" == "debian" ] ; then
-      APT_UPDATE='env LANG=C.UTF-8 apt-get update -o Acquire::GzipIndexes=false'
-      APT_INSTALL="env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef --no-install-recommends"
-      APT_UPGRADE="env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef --no-install-recommends"
 
-      # ====== Prepare container ============================================
-      echo "###### Preparing container ... ########################################"
-      # Use uncompressed package lists. Necessary to work around
-      # "apt-show-version" problems due to usage of compressed lists in
-      # Docker containers:
-      # https://askubuntu.com/questions/916199/install-apt-show-versions-inside-an-ubuntu-docker-container
-      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 \
-         sed -e "s#http://archive.ubuntu.com/ubuntu/#http://${UBUNTU_MIRROR}/ubuntu/#g" -i /etc/apt/sources.list
-      sudo docker exec ${CONTAINER} bash -c "find /var/lib/apt/lists/ -maxdepth 1 -type f | xargs rm -f"
-      sudo docker exec ${CONTAINER} ${APT_UPDATE}
+   # ====== Docker ==========================================================
+   if [ "${DOCKER}" != "" ] ; then
 
-      echo "Installing eatmydata ..."
-      echo sudo docker exec ${CONTAINER} ${APT_INSTALL} eatmydata python3 software-properties-common
-      sudo docker exec ${CONTAINER} ${APT_INSTALL} eatmydata python3 software-properties-common
-
-      distribution=`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 lsb_release -cs | sed -e "s/[^0-9a-zA-Z]//g"`
-      if [ "${VARIANT}" == "debian" ] ; then
-         if [[ "$DOCKER" =~ ^(debian:)(.*)$ ]] ; then
-            distribution="${BASH_REMATCH[2]}"
-         fi
-      fi
-      echo "distribution=$distribution"
-
-      if [ "${VARIANT}" == "ubuntu" ] ; then
-         mirror="http://${UBUNTU_MIRROR}/ubuntu/"
-      else
-         mirror="http://deb.debian.org/debian"
-      fi
-      echo "mirror=$mirror"
-
-
-      # ====== Ubuntu/Debian: add repositories (dreibh:ppa, backports, updates) ===
-      echo "###### Adding dreibh:ppa, backports, updates to container ... ###############"
-      if [ "${VARIANT}" == "ubuntu" ] ; then
-         echo "Ubuntu: adding adding ppa:dreibh/ppa and ${distribution}-backports ..."
-         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 apt-add-repository -y ppa:dreibh/ppa
-         sudo docker exec ${CONTAINER} eatmydata ${APT_UPDATE}
-      fi
+      # ====== Ubuntu Linux =================================================
       if [ "${VARIANT}" == "ubuntu" -o "${VARIANT}" == "debian" ] ; then
-         echo "Ubuntu/Debian: adding ${distribution}-backports ..."
-         # NOTE: backports may be unavailable -> ignore error on apt-get update!
-         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 apt-add-repository "deb ${mirror} ${distribution}-updates main universe"
-         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 apt-add-repository "deb ${mirror} ${distribution}-backports main universe"
-         sudo docker exec ${CONTAINER} eatmydata ${APT_UPDATE} || true
-         sudo docker exec ${CONTAINER} eatmydata ${APT_UPGRADE}
-      fi
+         APT_UPDATE='env LANG=C.UTF-8 apt-get update -o Acquire::GzipIndexes=false'
+         APT_INSTALL="env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef --no-install-recommends"
+         APT_UPGRADE="env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef --no-install-recommends"
+
+         # ====== Prepare container =========================================
+         echo "###### Preparing container ... ########################################"
+         # Use uncompressed package lists. Necessary to work around
+         # "apt-show-version" problems due to usage of compressed lists in
+         # Docker containers:
+         # https://askubuntu.com/questions/916199/install-apt-show-versions-inside-an-ubuntu-docker-container
+         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 \
+            sed -e "s#http://archive.ubuntu.com/ubuntu/#http://${UBUNTU_MIRROR}/ubuntu/#g" -i /etc/apt/sources.list
+         sudo docker exec ${CONTAINER} bash -c "find /var/lib/apt/lists/ -maxdepth 1 -type f | xargs rm -f"
+         sudo docker exec ${CONTAINER} ${APT_UPDATE}
+
+         echo "Installing eatmydata ..."
+         echo sudo docker exec ${CONTAINER} ${APT_INSTALL} eatmydata python3 software-properties-common
+         sudo docker exec ${CONTAINER} ${APT_INSTALL} eatmydata python3 software-properties-common
+
+         distribution=`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 lsb_release -cs | sed -e "s/[^0-9a-zA-Z]//g"`
+         if [ "${VARIANT}" == "debian" ] ; then
+            if [[ "$DOCKER" =~ ^(debian:)(.*)$ ]] ; then
+               distribution="${BASH_REMATCH[2]}"
+            fi
+         fi
+         echo "distribution=$distribution"
+
+         if [ "${VARIANT}" == "ubuntu" ] ; then
+            mirror="http://${UBUNTU_MIRROR}/ubuntu/"
+         else
+            mirror="http://deb.debian.org/debian"
+         fi
+         echo "mirror=$mirror"
 
 
-      # ====== Ubuntu/Debian: extract dependencies ==========================
-      echo "###### Obtaining build dependencies ... ###############################"
-      echo "Extracting dependencies ..."
-      UBUNTU_DEPS=`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 ci/get-dependencies ${VARIANT}`
-      echo "Dependencies: ${UBUNTU_DEPS}"
+         # ====== Ubuntu/Debian: add repositories (dreibh:ppa, backports, updates)
+         echo "###### Adding dreibh:ppa, backports, updates to container ... ###############"
+         if [ "${VARIANT}" == "ubuntu" ] ; then
+            echo "Ubuntu: adding adding ppa:dreibh/ppa and ${distribution}-backports ..."
+            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 apt-add-repository -y ppa:dreibh/ppa
+            sudo docker exec ${CONTAINER} eatmydata ${APT_UPDATE}
+         fi
+         if [ "${VARIANT}" == "ubuntu" -o "${VARIANT}" == "debian" ] ; then
+            echo "Ubuntu/Debian: adding ${distribution}-backports ..."
+            # NOTE: backports may be unavailable -> ignore error on apt-get update!
+            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 apt-add-repository "deb ${mirror} ${distribution}-updates main universe"
+            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 apt-add-repository "deb ${mirror} ${distribution}-backports main universe"
+            sudo docker exec ${CONTAINER} eatmydata ${APT_UPDATE} || true
+            sudo docker exec ${CONTAINER} eatmydata ${APT_UPGRADE}
+         fi
 
 
-      # ====== Ubuntu/Debian: set up compiler ===============================
-      if [ "${TOOL}" == "compile" ] ; then
-         echo "###### Installing compile environment ... #############################"
-         sudo docker exec ${CONTAINER} eatmydata ${APT_INSTALL} build-essential joe clang ${UBUNTU_DEPS}
+         # ====== Ubuntu/Debian: extract dependencies =======================
+         echo "###### Obtaining build dependencies ... ###############################"
+         echo "Extracting dependencies ..."
+         UBUNTU_DEPS=`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 ci/get-dependencies ${VARIANT}`
+         echo "Dependencies: ${UBUNTU_DEPS}"
 
 
-      # ====== Ubuntu/Debian: set up pbuilder ===============================
-      elif [ "${TOOL}" == "pbuilder" ] ; then
-         echo "###### Installing pbuilder environment ... ############################"
-         sudo docker exec ${CONTAINER} eatmydata ${APT_INSTALL} \
-            joe build-essential devscripts fakeroot lintian pbuilder python3-debian sudo ${UBUNTU_DEPS}
+         # ====== Ubuntu/Debian: set up compiler ============================
+         if [ "${TOOL}" == "compile" ] ; then
+            echo "###### Installing compile environment ... #############################"
+            sudo docker exec ${CONTAINER} eatmydata ${APT_INSTALL} build-essential joe clang ${UBUNTU_DEPS}
 
-         # ====== pbuilder environment ======================================
-         echo "###### Setting up pbuilder ... ########################################"
-         sudo docker exec ${CONTAINER} bash -c "env LANG=C.UTF-8 cat >/etc/pbuilderrc <<EOF
+
+         # ====== Ubuntu/Debian: set up pbuilder ============================
+         elif [ "${TOOL}" == "pbuilder" ] ; then
+            echo "###### Installing pbuilder environment ... ############################"
+            sudo docker exec ${CONTAINER} eatmydata ${APT_INSTALL} \
+               joe build-essential devscripts fakeroot lintian pbuilder python3-debian sudo ${UBUNTU_DEPS}
+
+            # ====== pbuilder environment ===================================
+            echo "###### Setting up pbuilder ... ########################################"
+            sudo docker exec ${CONTAINER} bash -c "env LANG=C.UTF-8 cat >/etc/pbuilderrc <<EOF
 DISTRIBUTION=\"${distribution}\"
 COMPONENTS=\"main universe\"
 MIRRORSITE=\"${mirror}\"
@@ -112,68 +116,91 @@ cores=\\\`getconf _NPROCESSORS_ONLN\\\`
 export CONCURRENCY_LEVEL=\\\${cores}
 export DEB_BUILD_OPTIONS=\"parallel=\\\${cores}\"
 EOF"
-         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 cat /etc/pbuilderrc
-         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 \
-            pbuilder create --debootstrapopts --variant=buildd
-         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 ls -l /var/cache/pbuilder/base.tgz
+            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 cat /etc/pbuilderrc
+            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 \
+               pbuilder create --debootstrapopts --variant=buildd
+            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 ls -l /var/cache/pbuilder/base.tgz
 
-         # ====== Add ppa:dreibh/ppa, updates and backports =================
-         if [ "${VARIANT}" == "ubuntu" ] ; then
-            echo "###### Adding dreibh:ppa to pbuilder ... ##############################"
-            echo "pbuilder Ubuntu: adding adding ppa:dreibh/ppa and ${distribution}-backports ..."
-            sudo docker exec ${CONTAINER} bash -c "env LANG=C.UTF-8 eatmydata pbuilder login --save-after-login <<EOF
+            # ====== Add ppa:dreibh/ppa, updates and backports ==============
+            if [ "${VARIANT}" == "ubuntu" ] ; then
+               echo "###### Adding dreibh:ppa to pbuilder ... ##############################"
+               echo "pbuilder Ubuntu: adding adding ppa:dreibh/ppa and ${distribution}-backports ..."
+               sudo docker exec ${CONTAINER} bash -c "env LANG=C.UTF-8 eatmydata pbuilder login --save-after-login <<EOF
 ${APT_INSTALL} software-properties-common
 apt-add-repository -y ppa:dreibh/ppa
 ${APT_UPDATE}
 EOF"
-            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 ls -l /var/cache/pbuilder/base.tgz
-         fi
+               sudo docker exec ${CONTAINER} env LANG=C.UTF-8 ls -l /var/cache/pbuilder/base.tgz
+            fi
 
-         if [ "${VARIANT}" == "ubuntu" -o "${VARIANT}" == "debian" ] ; then
-            echo "###### Adding backports and updates to pbuilder ... ###################"
+            if [ "${VARIANT}" == "ubuntu" -o "${VARIANT}" == "debian" ] ; then
+               echo "###### Adding backports and updates to pbuilder ... ###################"
 
-            # NOTE: backports may be unavailable -> ignore error on apt-get update!
-            sudo docker exec ${CONTAINER} bash -c "env LANG=C.UTF-8 eatmydata pbuilder login --save-after-login <<EOF
+               # NOTE: backports may be unavailable -> ignore error on apt-get update!
+               sudo docker exec ${CONTAINER} bash -c "env LANG=C.UTF-8 eatmydata pbuilder login --save-after-login <<EOF
 ${APT_INSTALL} software-properties-common
 apt-add-repository \"deb ${mirror} ${distribution}-updates main universe\"
 apt-add-repository \"deb ${mirror} ${distribution}-backports main universe\"
 ${APT_UPDATE} || true
 ${APT_UPGRADE}
 EOF"
-            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 ls -l /var/cache/pbuilder/base.tgz
+               sudo docker exec ${CONTAINER} env LANG=C.UTF-8 ls -l /var/cache/pbuilder/base.tgz
+            fi
+
+         else
+            echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
+            exit 1
          fi
 
+         echo "###### Finished setup of build environment ############################"
+
+
+      # ======Fedora Core Linux =============================================
+      elif [ "${VARIANT}" == "fedora" ] ; then
+         FEDORA_DEPS="`ci/get-dependencies ${VARIANT}`"
+
+         # ====== Fedora: set up compiler ===================================
+         if [ "${TOOL}" == "compile" ] ; then
+            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 \
+               dnf install -y make clang ${FEDORA_DEPS}
+
+         # ====== Fedora: set up pbuilder ===================================
+         elif [ "${TOOL}" == "mock" ] ; then
+            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 \
+               dnf install -y make findutils fedora-release mock rpmdevtools ${FEDORA_DEPS}
+
+         else
+            echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
+            exit 1
+         fi
+
+      # ======Fedora Core Linux ================================================
       else
-         echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
+         echo >&2 "ERROR: Invalid setting of VARIANT=${VARIANT}"
          exit 1
       fi
 
-      echo "###### Finished setup of build environment ############################"
 
-
-   # ======Fedora Core Linux ================================================
-   elif [ "${VARIANT}" == "fedora" ] ; then
-      FEDORA_DEPS="`ci/get-dependencies ${VARIANT}`"
-
-      # ====== Fedora: set up compiler ======================================
-      if [ "${TOOL}" == "compile" ] ; then
-         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 \
-            dnf install -y make clang ${FEDORA_DEPS}
-
-      # ====== Fedora: set up pbuilder ======================================
-      elif [ "${TOOL}" == "mock" ] ; then
-         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 \
-            dnf install -y make findutils fedora-release mock rpmdevtools ${FEDORA_DEPS}
-
-      else
-         echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
-         exit 1
-      fi
-
-   # ======Fedora Core Linux ================================================
+   # ====== Travis CI standard Ubuntu Linux machine =========================
+   # That is: not using Docker
    else
-      echo >&2 "ERROR: Invalid setting of VARIANT=${VARIANT}"
-      exit 1
+      sudo apt-get update
+      sudo ci/get-dependencies ubuntu --install
+
+      # ====== Coverity Scan ================================================
+      if [ "${TOOL}" == "coverity" ] ; then
+         mkdir coverity
+         cd coverity
+         wget --no-verbose https://scan.coverity.com/download/linux64 --post-data "token=${COVERITY_SCAN_TOKEN}&project=${COVERITY_PROJECT}" -O coverity_tool.tar.gz
+         if [ $? -ne 0 ] ; then
+            echo 2>&1 "ERROR: Download of Coverity Scan analysis tool failed!"
+            exit 1
+         fi
+         tar xzf coverity_tool.tar.gz
+         rm -f coverity_tool.tar.gz
+         cd ..
+      fi
+
    fi
 
 
