Updated CI workflow.

diff --git a/ci/ci-setup b/ci/ci-setup
--- a/ci/ci-setup
+++ b/ci/ci-setup
@@ -1,7 +1,17 @@
 #!/usr/bin/env bash
+# ==========================================================================
+#              ____        _ _     _     _____           _
+#             | __ ) _   _(_) | __| |   |_   _|__   ___ | |___
+#             |  _ \| | | | | |/ _` |_____| |/ _ \ / _ \| / __|
+#             | |_) | |_| | | | (_| |_____| | (_) | (_) | \__ \
+#             |____/ \__,_|_|_|\__,_|     |_|\___/ \___/|_|___/
+#
+#                           --- Build-Tools ---
+#                https://www.nntb.no/~dreibh/system-tools/
+# ==========================================================================
 #
 # GitHub Actions Scripts
-# Copyright (C) 2021-2025 by Thomas Dreibholz
+# Copyright (C) 2021-2026 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -23,10 +33,23 @@ set -eu
 
 
 # ====== Check arguments ====================================================
+if [ $# -lt 1 ] ; then
+   echo >&2 "Usage: $0 compile|package ..."
+   exit 1
+fi
+
+
+# ====== Check arguments ====================================================
 USE_PACKAGING=0
 while [ $# -gt 0 ] ; do
-   if [ "$1" == "package" ] ; then
+   TOOL="$1"
+   if [ "${TOOL}" == "compile" ] ; then
+      USE_PACKAGING=0
+   elif [ "$1" == "package" ] ; then
       USE_PACKAGING=1
+   else
+      echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}!"
+      exit 1
    fi
    shift
 done
@@ -52,7 +75,7 @@ if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
    fi
    if [ ${USE_PACKAGING} -eq 1 ] ; then
       # Need to install pbuilder as well:
-      PACKAGES="${PACKAGES} build-essential debian-archive-keyring debian-ports-archive-keyring devscripts distro-info eatmydata fakeroot pbuilder qemu-user-static sudo"
+      PACKAGES="${PACKAGES} build-essential debian-archive-keyring debian-ports-archive-keyring devscripts distro-info eatmydata fakeroot pbuilder qemu-user qemu-user-binfmt sudo"
    fi
 
    apt-get update -qq
@@ -61,6 +84,8 @@ if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
    DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef --no-install-recommends \
       ${PACKAGES}
 
+   # ====== Add COPR PPA dreibh/ppa =========================================
+   # NOTE: This is only available for Ubuntu!
    if [ "${ID}" == "ubuntu" ] ; then
       # Add PPA dreibh/ppa for Ubuntu:
       DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef --no-install-recommends \
@@ -152,12 +177,11 @@ EOF
       echo "echo \"force-unsafe-io\" > /etc/dpkg/dpkg.cfg.d/02apt-speedup" | \
          OS="${OS}" DISTRIBUTION="${DIST}" ARCHITECTURE="${ARCH}" pbuilder login --save-after-exec
 
-      # ====== Add ppa:dreibh/ppa, updates and backports =================
+      # ====== Add PPA dreibh/ppa ===========================================
       if [ "${OS}" == "ubuntu" ] ; then
          # Add PPA dreibh/ppa for Ubuntu:
          OS="${OS}" DISTRIBUTION="${DIST}" ARCHITECTURE="${ARCH}" pbuilder login --save-after-login <<EOF
-DEBIAN_FRONTEND=noninteractive apt-get install -qqy -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef --no-install-recommends \
-software-properties-common
+DEBIAN_FRONTEND=noninteractive apt-get install -qqy -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef --no-install-recommends software-properties-common
 apt-add-repository -y ppa:dreibh/ppa
 apt-get update -q
 EOF
@@ -172,6 +196,9 @@ elif [ "${ID}" == "fedora" ] ; then
       # Need to install mock as well:
       PACKAGES="${PACKAGES} fedora-release findutils mock nosync rpmdevtools   which strace sudo"
    fi
+
+   # ====== Add COPR PPA dreibh/ppa =========================================
+   dnf copr enable -y dreibh/ppa
 
    # dnf upgrade -qy
    # shellcheck disable=SC2086
@@ -191,9 +218,10 @@ elif [ "${ID}" == "fedora" ] ; then
          ARCH="$(uname -m)"
       fi
 
+      # ====== Enable COPR PPA ==============================================
       if ! grep "^\[copr-dreibh-ppa\]" "/etc/mock/${OS}-${DIST}-${ARCH}.cfg" ; then
          shopt -s extglob
-         ppa="config_opts['dnf.conf'] += \"\"\"\n[copr-dreibh-ppa]\nname=Copr repo for ppa owned by dreibh\nbaseurl=https://copr-be.cloud.fedoraproject.org/results/dreibh/ppa/fedora-\$releasever-\$basearch/\ntype=rpm-md\nskip_if_unavailable=True\ngpgcheck=1\ngpgkey=https://copr-be.cloud.fedoraproject.org/results/dreibh/ppa/pubkey.gpg\nrepo_gpgcheck=0\nenabled=1\n\"\"\""
+         ppa="config_opts['dnf.conf'] += \"\"\"\n[copr-dreibh-ppa]\nname=Copr repo for ppa owned by dreibh\nbaseurl=https://download.copr.fedorainfracloud.org/results/dreibh/ppa/fedora-\$releasever-\$basearch/\ntype=rpm-md\nskip_if_unavailable=True\ngpgcheck=1\ngpgkey=https://copr-be.cloud.fedoraproject.org/results/dreibh/ppa/pubkey.gpg\nrepo_gpgcheck=0\nenabled=1\nenabled_metadata=1\n\"\"\""
          ppa="${ppa//+( )$/\\n}"
          echo -e "${ppa}" | tee -a "/etc/mock/${OS}-${DIST}-${ARCH}.cfg"
          if ! grep "^\[copr-dreibh-ppa\]" "/etc/mock/${OS}-${DIST}-${ARCH}.cfg" ; then
