Improved CI scripts.

diff --git a/ci/test b/ci/test
--- a/ci/test
+++ b/ci/test
@@ -19,7 +19,7 @@
 # Contact: dreibh@iem.uni-due.de
 
 
-CONTAINER="ubuntu-test"
+. `dirname $0`/get-container
 
 
 # ###### Linux ##############################################################
@@ -53,13 +53,16 @@ if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
          fi
 
          echo "Installing ${packages} ..."
-         # NOTE: Older "apt-get" versions do not handle local files!
-         if ! sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive dpkg -i ${packages} ; then
-            echo "There may be some dependencies missing. Trying to install them ..."
-            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive apt-get install -fy -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" --no-install-recommends
-            echo "Retrying to install ${packages} ..."
-            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive dpkg -i ${packages}
-         fi
+         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive apt-get install -fy ${packages} || {
+            echo "NOTE: apt-get failed -> trying dpkg instead of apt-get for local file!"
+            # NOTE: Older "apt-get" versions do not handle local files!
+            if ! sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive dpkg -i ${packages} ; then
+               echo "There may be some dependencies missing. Trying to install them ..."
+               sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive apt-get install -fy -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" --no-install-recommends
+               echo "Retrying to install ${packages} ..."
+               sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive dpkg -i ${packages}
+            fi
+         }
          echo "Done!"
 
       # ====== mock environment =============================================
